/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#define RCC_BASE 0x4002100
#define GPIOA_BASE 0x40010800


#define RCC_APB2ENR *(volatile uint32_t *) (RCC_BASE + 0x18)
#define GPIO_CRH  *(volatile uint32_t *) (GPIOA_BASE + 0x04)
#define GPIO_ODR  *(volatile uint32_t *) (GPIOA_BASE + 0x0C)

#define RCC_IOPAEN (1<<2)
#define GPIOA13 (1UL << 13)

typedef union {
	int32_t all_fields;
	struct{
		int32_t reserved:13 ;
		int32_t pin13:1 ;
	}pin;

}R_ODR_t;

volatile R_ODR_t* R_ODR = (volatile R_ODR_t*) (GPIOA_BASE + 0x0C) ;
uint8_t g_variable[3] = {1,2,3};
uint8_t const gc_variable[3] = {1,2,3};

int main(void)
{
	RCC_APB2ENR |= RCC_IOPAEN;
	GPIO_CRH &= 0xff0fffff;
	GPIO_CRH |=0x00200000;
	while(1)
	{
		R_ODR->pin.pin13 =1;
		//GPIO_ODR |= 1 <<13;
		for (int i =0 ; i <5000 ; i++);
		//GPIO_ODR &= ~( 1 <<13);
		R_ODR->pin.pin13 =0;
		for (int i =0 ; i <5000 ; i++);

	}
	return 0;
}
